name: FTP-Service
services:
    proftpd:
        image: kibatic/proftpd:latest
        container_name: ftp-server
        ports:
            - 21:21
            - 50000-50010:50000-50010
        volumes:
            - /home/alumno/servicios/FTP/FTP-HOME:/home/alumno
        environment:
            - FTP_LIST=alumno:alumno
            - PASSIVE_MIN_PORT=50000
            - PASSIVE_MAX_PORT=50010