apiVersion: v1
kind: Service
metadata:
  name: dorayakiweb-service
  namespace: dorayakiweb
spec:
  type: ClusterIP
  selector:
    app: dorayakiweb
  ports:
    - name: http
      port: 80
      targetPort: 80
    # - name: https 
    #   port: 443
    #   targetPort: 443
