apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorayakiweb
  namespace: dorayakiweb
  labels:
    app: dorayakiweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dorayakiweb
  template:
    metadata:
      labels:
        app: dorayakiweb
    spec:
      containers:
        - name: dorayakiweb
          image: dorayakiweb-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            #- containerPort: 443
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
